### ISSUE TITLE
[REQ] Suggestion of modules for VIP

### ISSUE THREAD

**Issue by crashzk** [partiusfabaa/cs2-VIPCore#14]
- [ ] Boost Ladder - https://hlmod.net/resources/vip-boost-ladder.389/
- [x] No Fall Damage - https://hlmod.net/resources/vip-no-fall-damage.867/
- [x] Fast Reload - https://hlmod.net/resources/vip-fast-reload.824/
- [ ] Skybox - https://github.com/samyycX/CS2-SkyboxChanger
- [ ] Paintball - https://hlmod.net/resources/vip-paintball.931/
- [x] Unlimited Ammo - https://hlmod.net/resources/vip-unlimited-ammo.613/
- Tag & ChatTag
   - [x] Tag
   - [ ] Chat Tag **_(with colors)_** - https://hlmod.net/resources/vip-tag.292/
- [ ] Auto Buy - https://hlmod.net/resources/vip-autobuy.1605/
- [ ] Join Hud Message - https://hlmod.net/resources/vip-join-hud-message.805/
- [x] Show Damage - https://hlmod.net/resources/vip-show-damage.1818/
   - Author [Iksix](https://github.com/Iksix): https://github.com/Iksix/VIP_ShowDamage
- [ ] No Self Damage - https://hlmod.net/resources/vip-no-self-damage.1802/
- [x] Damage Change https://hlmod.net/resources/vip-damage-change.219/

**Comment by pandathebeasty** [comment]
https://github.com/Iksix/VIP_ShowDamage

for show damage

**Comment by crashzk** [comment]
Good, I added the link and marked it as done, let @partiusfabaa check it and decide whether to add it to your repository.

**Comment by Mikasan15** [comment]
Skins - https://hlmod.net/resources/vip-skins.1002/
Pets - https://hlmod.net/resources/vip-pets.507/
