### ISSUE TITLE
[REQ] New modules for VIP Core

### ISSUE THREAD

**Issue by pandathebeasty** [partiusfabaa/cs2-VIPCore#15]
- [x] Unlimited Ammo - https://hlmod.net/resources/vip-unlimited-ammo.613/
- [ ] Tag & ChatTag(with colors) - https://hlmod.net/resources/vip-tag.292/
- [ ] Auto Buy - https://hlmod.net/resources/vip-autobuy.1605/
- [ ] JoinHudMessage - https://hlmod.net/resources/vip-join-hud-message.805/
- [ ] Show Damage - https://hlmod.net/resources/vip-show-damage.1818/
- [ ] No Self Damage - https://hlmod.net/resources/vip-no-self-damage.1802/
- [ ] Damage Change https://hlmod.net/resources/vip-damage-change.219/
- [ ] No Fall Damage -  https://hlmod.net/resources/vip-no-fall-damage.867/

**Comment by crashzk** [comment]
Duplicate: https://github.com/partiusfabaa/cs2-VIPCore/issues/14
