### ISSUE TITLE
[REQ] Improvements to VIP messages

### ISSUE THREAD

**Issue by crashzk** [partiusfabaa/cs2-VIPCore#2]
Some messages are sent with the name of the VIP group, but standardized, all as VIP in this case.

![image](https://github.com/partiusfabaa/cs2-VIPCore/assets/32937653/585d0dd2-7aa3-4a81-a385-ed32087256ca)

An option would be possible, key `{GROUPNAME}` something like this, to send in this case the name of the VIP group that we create in the config, example:

```
"vip.Expires": "Your {blue}{GROUPNAME}{default} status expires {blue}{0}",
```
 And then messages would be sent based on the name of the groups:
```
"Your {blue}VIP{default} status expires {blue}{0}",
"Your {blue}PREMIUM{default} status expires {blue}{0}",
"Your {blue}VIP II{default} status expires {blue}{0}",
```

**Comment by partiusfabaa** [comment]
all right, I'll do it!
