### ISSUE TITLE
Accroding cs2-VIPCore plugin - give example of what "features": values I can put to vip.json file?

### ISSUE THREAD

**Issue by flarmn** [partiusfabaa/cs2-VIPCore#25]
Hello! Thank you grealty for your plugin! But can you give example of what "features": values I can put to vip.json file? For beginner admins it hard to find all possible keys in your object to set VIP abilities correctly.
Waiting for your answer very much.

**Comment by partiusfabaa** [comment]
Go to this link(https://github.com/partiusfabaa/cs2-VIPCore/tree/main/VIPCore/modules), look for the module you need. Then go to the path(https://github.com/partiusfabaa/cs2-VIPCore/tree/main/VIPCore/modules/VIP_AntiFlash/build) (I took antiflash as an example) Go to the build folder and there is what you need to write in the config.
![image](https://github.com/partiusfabaa/cs2-VIPCore/assets/96542489/7e0d1f65-eb28-4ab6-a141-619433312169)

**Comment by flarmn** [comment]
Thank you greatly for your answer!  Do I need to copy the content of, as example, AntiFlash module directory to VipCore/Modules directory on my CS2 server before putting string "Antiflash":2 to vip.json?

**Comment by partiusfabaa** [comment]
no, you need to put the modules in counterstrikesharp/plugin/
