### ISSUE TITLE
VipApi OnPlayerLoaded - можно ли использовать в других плагинах?

### ISSUE THREAD

**Issue by WeirdPhrog** [partiusfabaa/cs2-VIPCore#32]
Приветствую. Есть ли простой способ использовать, например, "форвард" OnPlayerLoaded в других плагинах для проверки VIP привилегий у игрока, не превращая этот другой плагин в модуль VIP?

**Comment by partiusfabaa** [comment]
Да, вам просто нужно получить АПИ вип, и подписаться на эвент `PlayerLoaded`

```cs
private readonly PluginCapability<IVipCoreApi> _pluginCapability = new("vipcore:core");

public override void OnAllPluginsLoaded(bool hotReload)
{
    _api = _pluginCapability.Get();
    if (_api == null) return;

    _api.PlayerLoaded += OnPlayerLoaded;
}

private void OnPlayerLoaded(CCSPlayerController player, string group)
{
}
```

**Comment by WeirdPhrog** [comment]
Спасибо, а что на счет IsClientVip ?

**Comment by partiusfabaa** [comment]
> Спасибо, а что на счет IsClientVip ?

Вы можете обращаться ко всей АПИшке с помощью `_api` которое вы получаете в `OnAllPluginsLoaded`
