### ISSUE TITLE
error

### ISSUE THREAD

**Issue by mayersgamer** [partiusfabaa/cs2-VIPCore#70]
12:27:16 [EROR] (cssharp:PluginManager) OnAllPluginsLoaded failed
System.IO.FileNotFoundException: Could not load file or assembly 'RanksApi, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.
File name: 'RanksApi, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'
   at VIP_ExperienceMultiplier.VipExperienceMultiplier.OnAllPluginsLoaded(Boolean hotReload)
   at CounterStrikeSharp.API.Core.Plugin.Host.PluginManager.Load() in /home/runner/work/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Core/Plugin/Host/PluginManager.cs:line 106

**Comment by partiusfabaa** [comment]
do you have [this](https://github.com/partiusfabaa/cs2-ranks) plugin installed?

**Comment by mayersgamer** [comment]
> do you have [this](https://github.com/partiusfabaa/cs2-ranks) plugin installed?

so that was the reason , can you give me a wiki page on how to install this modules ?

![Screenshot 2024-10-05 172517](https://github.com/user-attachments/assets/c9d6da1f-3985-495b-93a3-65d3753fe5a2)
![Screenshot 2024-10-05 170956](https://github.com/user-attachments/assets/ff4cb03f-108c-42dd-b4e5-778f84202cde)
![Screenshot 2024-10-05 170945](https://github.com/user-attachments/assets/186a1189-c3c3-46d8-b8bb-ed5872ffe797)

**Comment by partiusfabaa** [comment]
after installing any of the modules, you must write in vip.json. What to write is specified in README.md of the module, for example: https://github.com/partiusfabaa/cs2-VIPCore/tree/main/VIPCore/modules/VIP_AntiFlash/build
![image](https://github.com/user-attachments/assets/b32e08fb-889c-4afe-9674-a133fcb9ac11)

**Comment by mayersgamer** [comment]
do you have a discord where you meet up and get ideas and donations ? 

i would pay if i get a module that allows vip player to pee on the player he just killed like 1.6 days : 
https://youtu.be/reI-lPmcLjo 🤭

**Comment by mayersgamer** [comment]
hey bro i tried this

**Comment by mayersgamer** [comment]
hey bro i tried diffrent configs but either vip core not loading or not showing modules in the list !vip

first try this way :
{
  "Delay": 2,
  "Groups": {
    "vip": {
      "FastReload": {"FastReload": true}
    }
  }
}

----------------------------------------------------
second try :

{
  "Delay": 2.0
  "Groups": {
    "VIP1": {
      "bhop": {
        "Timer": 5.0,
	"MaxSpeed": 350
      },
      "FastReload": {
        "FastReload": true
      }
    }
  }
}

**Comment by partiusfabaa** [comment]
```json
{
    "Delay": 2,
    "Groups": {
        "VIP1": {
            "Values": {
                "bhop": {
                    "Timer": 5,
                    "MaxSpeed": 350
                },
                "FastReload": {
                    "FastReload": true
                }
            }
        }
    }
}
```

**Comment by mayersgamer** [comment]
Hello and thank you for Help 

can you check this video i made a video example about fast reload and fast plant both enabled but i see no diffrence 
everything is loaded correctly.

https://youtu.be/RYGjqV_k-Lk

**Comment by partiusfabaa** [comment]
```json
{
    "Delay": 2,
    "Groups": {
        "vip": {
            "Values": {
                "bhop": {
                    "Timer": 5,
                    "MaxSpeed": 350
                },
               "SmokeColor": [ 1, 255, 1 ]
               "Zeus": 1
               "fastplant": true
               "FastReload": true
            }
        }
    }
}
```

you dont have to write things like
```json
"SmokeColor": {
    "SmokeColor": [ 1, 255, 1 ]
},
"Zeus": {
    "Zeus": 1
},
"fastplant": {
    "fastplant": true
},
"FastReload": {
    "FastReload": true
}
```

you should prescribe as in the module description

**Comment by mayersgamer** [comment]
Got you ! now its working.

but does bhop work tho ? i jump and i feel no diff  how does it work ?

**Comment by mayersgamer** [comment]
can you help with infinit ammo 
```
InfiniteAmmo: {
"Type" : 2,
"DisabledGuns": []
}
```

its breaking vip core loading .
