### ISSUE TITLE
При открытом меню повторный ввод команды !x не переключает функцию.

### ISSUE THREAD

**Issue by VOLKRuS** [partiusfabaa/cs2-VIPCore#8]
![image](https://github.com/partiusfabaa/cs2-VIPCore/assets/22769974/1f30315c-de0c-42d2-b0b0-0ebca070549d)
Всё в названии) И ещё, стоит ли ждать менюшку в худе? Некоторые плагины уже начали на неё переходить.

Edit. Оказалось, менюшку достаточно просто было переделать. Меню теперь HTML, само переоткрывается и корректно свопает вкл/выкл, при многократном нажатии. 
![image](https://github.com/partiusfabaa/cs2-VIPCore/assets/22769974/d8400ecb-1a04-438b-a730-f1ac3aa5ffe8)
Можешь написать в дискорд volk_rus, скину исходник.

**Comment by VOLKRuS** [comment]
Хоть и добавили HTML меню, оно при выборе любого пункта всё ещё закрывается и не даёт адекватно включить/выключить функцию, не переоткрывая меню.
![image](https://github.com/partiusfabaa/cs2-VIPCore/assets/22769974/48acb6ab-90cc-491b-abb7-e6b6b6a92cb9)

**Comment by partiusfabaa** [comment]
are u happy with the latest update? Is it now possible to close issues?
